### ISSUE TITLE
Improve documentation on TypedSvg.Extra.InPx

### ISSUE THREAD

**Issue by berry** [canadaduane/typed-svg#1]
I had just written my own 'centeredImage' when I discovered the function within TypedSvg. I like TypedSvg a lot. It improves the readability and usability of my Svg code a lot. Thanks! But, please improve the documentation on the function centeredImage. I now had to look in the source code to find out what every float means:

centeredImage href w_ h_ x_ y_

Whereby w_ and h_ are the width and height of the image and x_ and y_ are the coordinates where the image is centered on.

Thanks,
Berry

**Comment by canadaduane** [comment]
Great! Can you make a pull request to help out? There are so many things
that need attention. I'd love to have it all documented.

**Comment by berry** [comment]
Okay. Will try to do

**Comment by berry** [comment]
Okay. Will try to create a pull request this weekend.

(Sorry, about the closing and reopening. Pushed to wrong button by mistake.)

**Comment by canadaduane** [comment]
No problem, and thanks!
